module ZenScriptTranspiler

open System
open System.Text
open System.Text.Json
open System.Text.Json.Serialization

// ==========================================
// 1. ABSTRACT SYNTAX TREE (AST) DEFINITIONS
// ==========================================

type ZenItem = {
    ModId: string
    ItemId: string
    Count: int
}

type ZenStatement =
    | AddShapedRecipe of name: string * output: ZenItem * matrix: ZenItem list list
    | RemoveRecipe of recipeName: string

// ==========================================
// 2. PARSER / AST BUILDER
// ==========================================

module Parser =
    /// Parse ZenScript item syntax: "<item:modid:item_name> * count"
    let parseItem (raw: string) : ZenItem =
        let parts = raw.Trim().Split('*')
        let count = if parts.Length > 1 then int (parts.[1].Trim()) else 1
        
        let identifier = parts.[0].Trim().Trim('<', '>').Replace("item:", "")
        let idParts = identifier.Split(':')
        
        { ModId = idParts.[0]; ItemId = idParts.[1]; Count = count }

    /// Mock parser converting raw script lines into AST nodes
    let parseLine (line: string) : ZenStatement option =
        if line.StartsWith("recipes.remove") then
            let name = line.Split('"').[1]
            Some (RemoveRecipe name)
        elif line.StartsWith("recipes.addShaped") then
            // For demo purposes: parses hardcoded addShaped structure
            let name = "custom_iron_block"
            let output = parseItem "<item:minecraft:iron_block>"
            let row = [ parseItem "<item:minecraft:iron_ingot>"; parseItem "<item:minecraft:iron_ingot>" ]
            Some (AddShapedRecipe (name, output, [ row; row ]))
        else
            None

// ==========================================
// 3. CODE GENERATORS (TRANSPILERS)
// ==========================================

// --- TARGET A: JSON TRANSPILER ---
type JsonRecipe = {
    [<JsonPropertyName("type")>] Type: string
    [<JsonPropertyName("name")>] Name: string
    [<JsonPropertyName("output")>] Output: string
    [<JsonPropertyName("count")>] Count: int
    [<JsonPropertyName("pattern")>] Pattern: string list list
}

module JsonTranspiler =
    let transpile (ast: ZenStatement list) : string =
        let jsonObjects = 
            ast |> List.choose (function
                | AddShapedRecipe (name, output, matrix) ->
                    let pattern = matrix |> List.map (List.map (fun item -> sprintf "%s:%s" item.ModId item.ItemId))
                    Some {
                        Type = "minecraft:crafting_shaped"
                        Name = name
                        Output = sprintf "%s:%s" output.ModId output.ItemId
                        Count = output.Count
                        Pattern = pattern
                    }
                | RemoveRecipe _ -> None
            )
        
        let options = JsonSerializerOptions(WriteIndented = true)
        JsonSerializer.Serialize(jsonObjects, options)

// --- TARGET B: DYNAMIC C# TRANSPILER ---
module CSharpTranspiler =
    let transpileStatement (stmt: ZenStatement) : string =
        match stmt with
        | RemoveRecipe recipeName ->
            sprintf "            RecipeRegistry.Remove(\"%s\");" recipeName

        | AddShapedRecipe (name, output, matrix) ->
            let sb = StringBuilder()
            sb.AppendLine(sprintf "            RecipeRegistry.AddShaped(\"%s\"," name) |> ignore
            sb.AppendLine(sprintf "                new ItemStack(\"%s:%s\", %d)," output.ModId output.ItemId output.Count) |> ignore
            sb.AppendLine("                new ItemStack[,] {") |> ignore
            
            for row in matrix do
                let rowItems = row |> List.map (fun i -> sprintf "new ItemStack(\"%s:%s\", %d)" i.ModId i.ItemId i.Count) |> String.concat ", "
                sb.AppendLine(sprintf "                    { %s }," rowItems) |> ignore
            
            sb.AppendLine("                });") |> ignore
            sb.ToString()

    let transpileToClass (className: string) (ast: ZenStatement list) : string =
        let sb = StringBuilder()
        sb.AppendLine("// Auto-generated by F# ZenScript Transpiler Engine") |> ignore
        sb.AppendLine("using System;") |> ignore
        sb.AppendLine("using System.Collections.Generic;") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine(sprintf "public class %s" className) |> ignore
        sb.AppendLine("{") |> ignore
        sb.AppendLine("    public static void RegisterAll()") |> ignore
        sb.AppendLine("    {") |> ignore
        
        for stmt in ast do
            sb.AppendLine(transpileStatement stmt) |> ignore

        sb.AppendLine("    }") |> ignore
        sb.AppendLine("}") |> ignore
        sb.ToString()

// ==========================================
// 4. EXECUTION DRIVER
// ==========================================

[<EntryPoint>]
let main _ =
    // Simulated ZenScript Source File
    let zenscriptInput = [
        "recipes.remove(\"minecraft:stick\");"
        "recipes.addShaped(\"custom_iron_block\", <item:minecraft:iron_block>, ...);"
    ]

    // Step 1: Parse to F# AST
    let astNodes = zenscriptInput |> List.choose Parser.parseLine

    printfn "=== 1. GENERATED JSON DATA STRUCTURE ==="
    let jsonOutput = JsonTranspiler.transpile astNodes
    printfn "%s" jsonOutput

    printfn "\n=== 2. GENERATED C# SOURCE CODE ==="
    let csharpOutput = CSharpTranspiler.transpileToClass "GeneratedZenRecipes" astNodes
    printfn "%s" csharpOutput

    0
