// Auto-generated by F# ZenScript Transpiler Engine
using System;
using System.Collections.Generic;

public class GeneratedZenRecipes
{
    public static void RegisterAll()
    {
            RecipeRegistry.Remove("minecraft:stick");

            RecipeRegistry.AddShaped("custom_iron_block",
                new ItemStack("minecraft:iron_block", 1),
                new ItemStack[,] {
                    { new ItemStack("minecraft:iron_ingot", 1), new ItemStack("minecraft:iron_ingot", 1) },
                    { new ItemStack("minecraft:iron_ingot", 1), new ItemStack("minecraft:iron_ingot", 1) },
                });

    }
}
